# Generated by Django 2.2.4 on 2019-08-03 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('players', models.CharField(max_length=500)),
                ('dealer', models.CharField(max_length=200)),
                ('pool', models.IntegerField(default=0)),
                ('deck', models.CharField(max_length=500)),
                ('cards_on_table', models.CharField(max_length=100)),
            ],
        ),
    ]
