# Generated by Django 2.2.4 on 2019-08-03 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_auto_20190803_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='table',
            field=models.IntegerField(null=True),
        ),
    ]
