# Generated by Django 2.2.4 on 2019-08-03 15:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_auto_20190803_1728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player', to=settings.AUTH_USER_MODEL, unique=True),
        ),
    ]
