# Generated by Django 2.2.4 on 2019-08-04 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0012_auto_20190804_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='player1',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='table',
            name='player2',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='table',
            name='player3',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='table',
            name='player4',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
