# Generated by Django 2.2.4 on 2019-08-05 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0019_auto_20190805_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='table',
            field=models.IntegerField(null=True),
        ),
    ]
