# Generated by Django 2.2.4 on 2019-08-06 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0030_table_game_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='table',
            old_name='game_status',
            new_name='game_state',
        ),
    ]
