# Generated by Django 2.2.4 on 2019-08-07 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0036_table_dealerb'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='table',
            name='dealerb',
        ),
    ]
