# Generated by Django 2.2.4 on 2019-08-08 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0048_remove_table_pool'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='pool',
            field=models.IntegerField(default=0),
        ),
    ]
