# Generated by Django 2.2.4 on 2019-08-08 06:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0050_table_dealerz'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='table',
            name='dealerz',
        ),
        migrations.AddField(
            model_name='table',
            name='dealer',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dealerz', to='game.Player'),
        ),
    ]
