# Generated by Django 2.2.4 on 2019-08-08 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0051_auto_20190808_0823'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='table',
            name='dealer',
        ),
    ]
