# Generated by Django 2.2.4 on 2019-08-08 07:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0053_table_dealer'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='big_blind',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='big_blind', to='game.Player'),
        ),
        migrations.AddField(
            model_name='table',
            name='small_blind',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='small_blind', to='game.Player'),
        ),
        migrations.AlterField(
            model_name='table',
            name='dealer',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dealer', to='game.Player'),
        ),
    ]
