# Generated by Django 2.2.4 on 2019-08-08 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0054_auto_20190808_0922'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='round_money',
            field=models.IntegerField(default=100),
        ),
    ]
