# Generated by Django 2.2.4 on 2019-08-08 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0055_player_round_money'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='round_money',
            field=models.IntegerField(default=0),
        ),
    ]
