# Generated by Django 2.2.4 on 2019-08-08 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0056_auto_20190808_1255'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='turn',
            field=models.IntegerField(default=0),
        ),
    ]
