# Generated by Django 2.2.4 on 2019-08-08 11:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0060_remove_table_turn'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='turn',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='turn', to='game.Player'),
        ),
    ]
